spring.datasource.url=jdbc:mysql://localhost:3306/uamishop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=uamishop
spring.datasource.password=uamishop


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Sin consola H2 en este perfil
spring.h2.console.enabled=false
